---
- name: Add Splunk index
  hosts: all
  become: yes
  vars:
    splunk_home: "{{ splunk_home | default('/opt/splunk') }}"
    splunkd_port: "{{ splunkd_port | default(8089) }}"
    splunk_user: "{{ splunk_user | default('splunk') }}"
    splunk_group: "{{ splunk_group | default('splunk') }}"
    index_name: ""
    maxDataSizeMB: ""
    datatype: ""
    file_path: ""
  tasks:
    - name: Ensure directory exists for indexes.conf
      file:
        path: "{{ file_path | dirname }}"
        state: directory
        owner: "{{ splunk_user }}"
        group: "{{ splunk_group }}"
        mode: "0755"

    - name: Ensure indexes.conf file exists
      file:
        path: "{{ file_path }}"
        state: touch
        owner: "{{ splunk_user }}"
        group: "{{ splunk_group }}"
        mode: "0644"

    - name: Add or update index stanza (maxDataSizeMB)
      ini_file:
        path: "{{ file_path }}"
        section: "{{ index_name }}"
        option: maxDataSizeMB
        value: "{{ maxDataSizeMB }}"
        state: present
        owner: "{{ splunk_user }}"
        group: "{{ splunk_group }}"
        mode: "0644"

    - name: Add or update index stanza (datatype)
      ini_file:
        path: "{{ file_path }}"
        section: "{{ index_name }}"
        option: datatype
        value: "{{ datatype }}"
        state: present
        owner: "{{ splunk_user }}"
        group: "{{ splunk_group }}"
        mode: "0644"
