---
- name: Add Splunk index
  hosts: all
  become: yes
  vars:
    index_name: ""
    maxDataSizeMB: ""
    datatype: ""
    file_path: ""
  tasks:
    - name: Ensure directory exists for indexes.conf
      file:
        path: "{{ file_path | dirname }}"
        state: directory
        owner: splunk
        group: splunk
        mode: "0755"

    - name: Ensure indexes.conf file exists
      file:
        path: "{{ file_path }}"
        state: touch
        owner: splunk
        group: splunk
        mode: "0644"

    - name: Add or update index stanza
      ini_file:
        path: "{{ file_path }}"
        section: "{{ index_name }}"
        option:
          maxDataSizeMB: "{{ maxDataSizeMB }}"
          datatype: "{{ datatype }}"
        state: present
        owner: splunk
        group: splunk
        mode: "0644"
