---
- name: Apply Indexer Cluster Bundle
  hosts: all
  become: yes
  vars:
    splunk_home: "/opt/splunk"
    splunk_username: ""
    splunk_password: ""

  tasks:
    - name: Apply cluster bundle
      shell: >
        {{ splunk_home }}/bin/splunk apply cluster-bundle
        --answer-yes
        -auth '{{ splunk_username }}:{{ splunk_password }}'
      become_user: splunk
      register: cmbundle_apply_result

    - name: Display cluster apply bundle results (stdout)
      debug:
        msg: "{{ cmbundle_apply_result.stdout.split('\n') }}"
      ignore_errors: yes

    - name: Display cluster apply bundle results (stderr)
      debug:
        msg: "{{ cmbundle_apply_result.stderr.split('\n') }}"
      ignore_errors: yes
