---
- name: Install Splunk App on Standalone
  hosts: all
  become: yes
  vars:
    splunk_home: "/opt/splunk"
    splunk_app_tarball: ""
    splunk_app_name: ""

  tasks:
    - name: Upload app tarball
      copy:
        src: "{{ splunk_app_tarball }}"
        dest: "/tmp/{{ splunk_app_name }}.tgz"

    - name: Install app using Splunk CLI
      shell: >
        {{ splunk_home }}/bin/splunk install app /tmp/{{ splunk_app_name }}.tgz -update 1
      become_user: splunk
      register: install_app_results

    - name: Display app install result (stdout)
      debug:
        msg: "{{ install_app_results.stdout.split('\n') }}"
      ignore_errors: yes

    - name: Display capp install result (stderr)
      debug:
        msg: "{{ install_app_results.stderr.split('\n') }}"
      ignore_errors: yes
