---
- name: Install Splunk App on SHC
  hosts: "{{ shc_deployer_node }}"
  become: yes
  vars:
    splunk_app_name: ""
    splunk_home: "/opt/splunk"

  tasks:
    - name: Upload app tarball
      ansible.builtin.copy:
        src: "{{ splunk_app_name }}.tgz"
        dest: "{{ splunk_home }}/etc/shcluster/apps/{{ splunk_app_name }}.tgz"

    - name: Extract app tarball
      ansible.builtin.unarchive:
        src: "{{ splunk_home }}/etc/shcluster/apps/{{ splunk_app_name }}.tgz"
        dest: "{{ splunk_home }}/etc/shcluster/apps/{{ splunk_app_name }}"
        remote_src: yes

    - name: Remove app tarball after extraction
      ansible.builtin.file:
        path: "{{ splunk_home }}/etc/shcluster/apps/{{ splunk_app_name }}.tgz"
        state: absent

    - name: Set ownership and permissions
      ansible.builtin.file:
        path: "{{ splunk_home }}/etc/shcluster/apps/{{ splunk_app_name }}"
        state: directory
        owner: splunk
        group: splunk
        recurse: yes
