---
- name: Remove Splunk App from SHC
  hosts: all
  become: yes
  vars:
    splunk_home: "{{ splunk_home | default('/opt/splunk') }}"
    splunkd_port: "{{ splunkd_port | default(8089) }}"
    splunk_user: "{{ splunk_user | default('splunk') }}"
    splunk_group: "{{ splunk_group | default('splunk') }}"
    splunk_app_name: ""
    app_destination: "/opt/splunk/etc/shcluster/apps"

  tasks:
    - name: Remove app directory
      file:
        path: "{{ app_destination }}/{{ splunk_app_name }}"
        state: absent
      when: inventory_hostname == shc_deployer_node

    - name: Remove app tarball if exists
      file:
        path: "{{ app_destination }}/{{ splunk_app_name }}.tgz"
        state: absent
      when: inventory_hostname == shc_deployer_node
