---
- name: Remove Splunk App from Standalone
  hosts: all
  become: yes
  vars:
    splunk_home: "/opt/splunk"
    splunk_app_name: ""

  tasks:
    - name: Remove app using Splunk CLI
      shell: >
        {{ splunk_home }}/bin/splunk remove app {{ splunk_app_name }}
      become_user: splunk
      ignore_errors: yes

    - name: Ensure app directory is removed
      file:
        path: "{{ splunk_home }}/etc/apps/{{ splunk_app_name }}"
        state: absent
