---
- name: Restart Splunk Service
  hosts: all
  become: yes
  vars:
    splunk_service_name: "{{ splunk_service_name | default('splunk') }}"
    splunkd_port: "{{ splunkd_port | default(8089) }}"
  tasks:
    - name: Restart the Splunk service
      systemd:
        name: "{{ splunk_service_name }}"
        state: restarted
      become_user: root

    - name: Wait for Splunk startup
      wait_for:
        port: "{{ splunkd_port }}"
        timeout: 120
      ignore_errors: yes

    - name: Verify the Splunk service status
      systemd:
        name: "{{ splunk_service_name }}"
        state: started
      become_user: root
      register: splunk_status

    - name: Display Splunk service status
      debug:
        msg: "Splunk service restart successful. Status: {{ splunk_status }}"
